### PR TITLE
add Ana-Rita-Gomes.yml

### PR DESCRIPTION
**Pull request by AnaRitaGomes-3**

### CODE REVIEW

**Comment by niskrev** [comment]
Hi Ana Rita, you should fill in your info in the file you created...

**Comment by AnaRitaGomes-3** [comment]
Sorry, I think I didn't save correctly.
Now I think it is correct.

Thanks,

Ana Rita Gomes

Obter Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by niskrev** [comment]
Hi Ana Rita

**Review by niskrev — CHANGES_REQUESTED** [review]
Hi Ana Rita, could you confirm that your info is in the file you added? The one I see is empty...
Thanks!

**Comment by niskrev** [comment]
Great! Thanks Ana Rita!

**Pull request merged**
